# Site settings
title: Hemerson Camargo
description: >-
  {idéias, tecnologias, práticas, .NET, Python, talvez Full Stack e um pouco de games}
lang: pt-BR
timezone: America/Sao_Paulo
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/hemerfc/hemerson.dev
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Hemerson Camargo
  username: hemerfc
  email: hemerfc@hotmail.com
  avatar: /assets/img/avatar.jpg

# Url settings
url: "https://hemerson.dev"
baseurl:
permalink: /:title/
google_analytics:
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
